"""
Implementation Generator Tool for creating Python code from design specifications.

This module provides a Strands Agent-based tool that generates idiomatic Python code
from a design specification document. This design-driven approach produces higher
quality implementations that capture the intent and architecture of the original code.
"""

import logging
from strands import tool
from .specialized_agents import python_implementation_specialist

logger = logging.getLogger(__name__)


@tool
def implementation_from_design_tool(design_specification: str, original_language: str, file_path: str) -> str:
    """
    Generate Python code that implements a design specification.
    
    This tool creates idiomatic Python code based on a design document rather than
    directly translating syntax. This approach produces more maintainable, Pythonic
    code that captures the intent and architecture of the original implementation.
    
    Args:
        design_specification: The design document generated by design_specification_tool
        original_language: The source language (e.g., "JavaScript", "Java") for context
        file_path: Original file path for naming context
        
    Returns:
        String containing the generated Python code
    """
    import time
    start_time = time.time()
    
    try:
        logger.info(f"[DESIGN-DRIVEN] Starting Python implementation generation")
        logger.info(f"[DESIGN-DRIVEN] Original language: {original_language}")
        logger.info(f"[DESIGN-DRIVEN] File path: {file_path}")
        logger.info(f"[DESIGN-DRIVEN] Design specification size: {len(design_specification)} characters")
        
        # Create the implementation prompt
        implementation_prompt = f"""Generate Python code that implements the following design specification:

{design_specification}

Original language: {original_language}
Original file path: {file_path}

Please provide complete, production-ready Python code that implements all functionality described in the design specification."""
        
        logger.debug(f"[DESIGN-DRIVEN] Invoking Python implementation specialist agent")
        
        # Generate the Python implementation using the pre-created specialist agent
        implementation_result = python_implementation_specialist(implementation_prompt)
        python_code = str(implementation_result)
        
        implementation_time = time.time() - start_time
        
        logger.info(f"[DESIGN-DRIVEN] Successfully generated Python implementation")
        logger.info(f"[DESIGN-DRIVEN] Python code size: {len(python_code)} characters")
        logger.info(f"[DESIGN-DRIVEN] Implementation generation time: {implementation_time:.2f} seconds")
        
        # Log code quality indicators
        has_imports = "import " in python_code or "from " in python_code
        has_docstrings = '"""' in python_code or "'''" in python_code
        has_type_hints = ": " in python_code and "->" in python_code
        has_functions = "def " in python_code
        has_classes = "class " in python_code
        
        logger.debug(f"[DESIGN-DRIVEN] Python code quality indicators - Imports: {has_imports}, "
                    f"Docstrings: {has_docstrings}, Type hints: {has_type_hints}, "
                    f"Functions: {has_functions}, Classes: {has_classes}")
        
        return python_code
        
    except Exception as e:
        implementation_time = time.time() - start_time
        error_msg = f"Python implementation generation failed: {str(e)}"
        logger.error(f"[DESIGN-DRIVEN] {error_msg}")
        logger.error(f"[DESIGN-DRIVEN] Failed after {implementation_time:.2f} seconds")
        logger.error(f"[DESIGN-DRIVEN] Will fall back to direct translation approach")
        return error_msg

